### ISSUE TITLE
Processamento Parcial AM (Article Meta)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_proc#1]
### Problema:

Hoje contamos com um processamento que coleta **todas** os dados, isso não é o ideal.
### Objetivo:

Precisamos melhorar o processamento para permitir a coleta parcial dos dados.
### Observação:

Verificar no **article meta** a melhor formar de coletarmos dados parciais.

**Comment by jfunez** [comment]
resolvido
