### ISSUE TITLE
Adicionar na transformação de fascículo o 'start_page_sequence'.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_proc#208]
As últimas versão do Xylose foi adicionado um número sequencial que indica que existe mais de um artigo começando na mesma página. 

Verificar a propriedade: **start_page_sequence** do  Xylose.

**Comment by jfunez** [comment]
@robertatakenaka este issue já foi resolvido por vc, certo?

**Comment by robertatakenaka** [comment]
sim

**Comment by jfunez** [comment]
resolvido
