### ISSUE TITLE
[Assets] Erro na introspecção dos paths dos ativos digitais dos artigos

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac_proc#325]
Ao extrair os paths de ativos digitais de artigos durante a transformação, o OPAC-PROC está buscando os arquivos em lugares errados.

Ex: PID `S0103-64402003000200005`

Link: https://opac.scielo.br/article/bdj/2003.v14n2/99-102/en/
Ativo com erro: `file:///F|/web/htdocs/app/data/img/bdj/v14n2/n2a05t01.gif`

É necessário:
- Corrigir a introspecção dos ativos pelo final do nome do arquivo
- Reprocessar os artigos que apresentaram problema

**Comment by jfunez** [comment]
Já foi resolvido
