### ISSUE TITLE
botão: "reprocessar XMLs" (Transform Article) não funciona mais

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_proc#351]
após refatorar a classe process não temos mais o metodo `.update` agora é `process_selected` que deve ser chamado no `opac_proc.web.views.transform.list_view` @ `TransformArticleListView.do_reprocess_xml_only`

**Comment by patymori** [comment]
Botão funcionando sem problemas. Caso algum erro ocorra, reabrimos o ticket.
