### ISSUE TITLE
Tratar os links para PDF dentro dos artigos cujo texto é publicado somente em PDF

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac_proc#380]
<img width="751" alt="captura de tela 2018-10-18 as 16 56 18" src="https://user-images.githubusercontent.com/505143/47180341-c1cc9c80-d2f6-11e8-8774-1a99fbba13ad.png">

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02761929000100003&lng=en&nrm=iso&tlng=pt

<img width="839" alt="captura de tela 2018-10-18 as 16 58 26" src="https://user-images.githubusercontent.com/505143/47180484-12dc9080-d2f7-11e8-8261-426addd2b752.png">

https://new.scielo.br/article/mioc/1929.v22n1/135-144/pt/

**Comment by patymori** [comment]
Resolvido em #390
