### ISSUE TITLE
Verificar alterações no arquivo .thrift andes de iniciar o processamento.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_proc#6]
### Problema:

Mudanças no arquivo .thrift pode afetar o processamento.
### Objetivo:

Adicionar recurso no processamento para identificar mudanças no arquivo .thrift e atualizar.

**Comment by jfunez** [comment]
estamos usando a lib: articlemetaapi, portanto não dependemos diretamente do arquivo `.thirft`. Somente precisamos atualizar a versão da lib no `requirements.txt`
