### ISSUE TITLE
[Processamento] Verficar/Corrigir extração, transformação e cargar de Metricas (analytics) da Coleção

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_proc#61]
#### Problema:

Precisamos validar que a importação de dados "[métricas da coleção](https://github.com/scieloorg/opac_schema/blob/master/opac_schema/v1/models.py#L229)" esteja sendo importado pelo processamento, nas diferentes fases: extração, transformação e carga e que estaja salvo de forma correta no modelo correspondente no banco do OPAC.

##### Objetivo:

Validar que a execução das diferentes fases do processamento da coleção esta importando as "métricas da coleção"

##### Validação (manual):

0. verificar qual coleção esta configurada para ser processada (nas configurações das apps);
1. coleta dos dados: consultar os totais mostrados ("Collection composition") no [analytics](http://analytics.scielo.org/?collection=spa) de Journals, Issues, Documents/Articles e Citations;
2. Iniciar o processo (importação) de **extração** da coleção;
2.1 Após finalizado, verificar no modelo de Coleção extraída (**e_collection** no banco) o campo "metrics", que tem os totais coletados no paso 0;
3. Iniciar o processo (importação) de **transformação** da coleção;
3.1 Após finalizado, verificar no modelo da Coleção transformada (**t_collection** no banco) o campo "metrics", que tem os totais coletados no paso 0;
4. Iniciar o processo (importação) de **carga** da coleção;
4.1 Após finalizado, verificar no modelo da Coleção carregada (**l_collection** no banco) o campo "metrics", que tem os totais coletados no paso 0;
5. Verficar na interface **web do OPAC**, na homepage, que tem os totais coletados no paso 0.

**Comment by brunousml** [comment]
@jfunez show de bola! 

👍
