### ISSUE TITLE
Problemas rodando am2opac em novo ambiente

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac_proc#70]
#### Problema:
- A porta padrão do AM na configuração do am2opac não foi alterada;
- Realizando um instalação nova num ambiente de produção, encontramos que ao rodar o am2opac esta dando erro pela falta de uma depenência (opac_ssm_api), o que aponta ao fato de precisar um stack SSM (em produção);
- Também o processamento do am2opac não esta rodando em background, o que dificulta a execução no shell do container.

#### Objetivo:
- [ ] Ajustar porta padrão do AM nas configurações do am2opac;
- [ ] Resolver a instalação da dependência que falta (opac_ssm_api);
- [ ] Montar um ambiente SSM, e acrescentar as configurações mínimas (host e porta) dessa nova instância na configuração do am2opac;
- [ ] Testar o am2opac num ambiente de produção';
- [ ] Realizar os ajustes no stack para as novas configurações;
- [ ]  mudar o am2opac para rodar em background (se for possível, caso contrario podemos testar com `&` no final do comando.

#### Test:
- após o setup no ambiente de produção rodar o am2opac no shell do contanier;
- verificar que os estáticos estão cadastrados normalmente na instância de SSM;
- verficar que o processamento finalizou sem erros e os dados foram importados;

**Comment by jamilatta** [comment]
Atualmente esse ticket é inválido.
