### ISSUE TITLE
Registrar PDF no SSM

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac_proc#80]
Na etapa de transformação, registrar os PDF no SSM e gravar as url

**Comment by jamilatta** [comment]
Para finalizar esse ticket é necessário alguns ajustes no bucket_name apontados pela equipe. 

O Bucket name deve ser composto por acron/VvolumeNnúmero.

Também existe um erro na coleta dos idiomas, estamos considerando o idioma do abstract. Devemos considerar somente o idiomas do artigo.

**Comment by jamilatta** [comment]
Reabri esse ticket para que eu possa aplicar a validação de unicidade nos PDFs. 

Em conversa com @jfunez decidimos o seguinte: 

1. Devemos gerar um checksum para os ativos com o objetivo de garantir a unicidade dos ativos, porém a unicidade do ativo é verdade somente para um coleção.

2. Adicionamos um novo método no OPAC_SSM_GRPC e no OPAC_SSM_API para que seja possível buscar por um asset através do checksum e qualquer outro meta dado existente no campos ``metadata``

3. No processamento (por hora do PDF) devemos adicionar a consistência perguntando primeiro para o banco se o asset com checksum ``X`` e com metadata ``XPTO`` existe, caso exista devemos utilizar o ativo já existente, caso contrário deve continuar com o cadastro.

**Importante:** Nesse formato a atualização dos meta dados do registro deve ser executada através da função ``opac_ssm_api.client.update_asset``.

**Outro ponto importante:** caso exista o ativo devemos sempre atualizar os meta dados, pois é bastante provável que o re-processamento seja apenas para atualizar metadados no ativo.
